### ISSUE TITLE
what is the best strategy for project granularity?

### ISSUE THREAD

**Issue by djafta** [djafta/jutil#1]
there is a standard way of working with many classes and files, which brings its facilities, but requires that whoever is going to use them, compile everything in a jar. The second way is to create a huge file (**JSON**) and put all the code in it, that way anyone who wants to fit it into a package of utilities in their project can do it without much concern.

Which of these two **strategies** would be beneficial?

**Comment by machavate** [comment]
Lately I've been working with JSON in web applications. And in java I've always used .jar to connect my application to the database "I use jdbc.jar". 

JSON is a compact format, with simple data transfer between systems.

JAR is a compressed file, used to distribute a set of Java classes. We have a very famous way of compression of files, the ZIP, we can compare to jar. It brings us security, first it's not easy to change it (it's possible to key), and the data is not scattered.

To answer the question, JSON is a strategy that for a moment gives us an advantage in the development environment.  

NB: I did not make a comparison between JSON and JAR just define i said which better strategy

**Comment by djafta** [comment]
So my question is, is it preferable to use a jar with many classes or just one class that can be freely downloaded and incorporated into your project?Thanks for your intervention, but I'm **not doing comparison** between jar and JSON.

Normally, you add a jar to your project to use the classes you have in it via import:
**example.project.Class**.

There's no way to change that, however assuming you want to put all the utilities in a **com.company.project.util** package, if the utility is a class with no dependencies, you can move it into that package.

So my question is, is it preferable to use a jar with many classes or just one class that can be freely downloaded and incorporated into your project?

**Comment by machavate** [comment]
Clearly! Just a class that can be freely downloaded and incorporated into your project. But don't forget the more granularity, the more space demanded and the more precision, that's why it's important to see the granularity

**Comment by djafta** [comment]
> Clearly! Just a class that can be freely downloaded and incorporated into your project. But don't forget the more granularity, the more space demanded and the more precision, that's why it's important to see the granularity

I didn't get the answer, could you explain?

**Comment by machavate** [comment]
![Screenshot_20230210-002245_Chrome](https://user-images.githubusercontent.com/82161016/217952821-f87606d6-6f2c-4f03-93db-32a834db52c5.jpg)

I am reconciling the topic you can check in the image, which talks about granularity

**Comment by machavate** [comment]
It's preferable to use jar with many classes!

**Comment by djafta** [comment]
Thank you for your reply @machavate. I will use **jar**
